version: "2"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - 8000:8000
    command: python -m epidemicalk
    volumes:
      - ./epidemicalk/:/app/epidemicalk:Z

  db:
    ports:
      - 5432:5432
